### ISSUE TITLE
The two cubes drag at the same time when place one on top of another

### ISSUE THREAD

**Issue by weiying-chen** [lwakefield/aframe-draggable-objs#1]
First of all, thanks for the example. It saved me many hours of work!

Only one thing is troubling me: when you place one cube on top of another and try to drag them, both cubes move: https://codepen.io/alexcheninfo/pen/vKkgkE

Is there a way to fix this?

**Comment by lwakefield** [comment]
Absolutely! For my purposes, I didn't really need this. But let me see if I can remember some stuff that I discovered along the way.

There is a [intersectObjects](http://threejs.org/docs/api/core/Raycaster.html) function that you can use to test over multiple objects.

You need to make sure that you use the recursive flag, because for instance a cube isn't an mesh, but a collection of meshes (the faces).

Then you have an array of intersections, which you can check the distances on, compare to the original object and handle from there.

**Comment by weiying-chen** [comment]
Thanks for replying. I did:

```
let intersected = r.intersectObject(this.el.object3D, true)
console.log(intersected)
```

But when the two cubes drags at the same time, I get two arrays with one object, instead of an array with two objects.

Could you give me an example code of your suggestion?

**Comment by lwakefield** [comment]
Hey there, [here is what I came up with](https://codepen.io/lwakefield/pen/bZvXGz?editors=1001).

It isn't the most efficient solution if you have lots of `draggable` objects. But if you only have a couple, it shouldn't be an issue.

**Comment by weiying-chen** [comment]
@lwakefield Thanks man! You saved my life.
